### ISSUE TITLE
Getting infinite loop when used on aws lambda

### ISSUE THREAD

**Issue by jeffepalmares** [manuth/CallerModule#3]
Hello I am using thins module on my project in a Aws Lambda, but it is getting in infinite loop when it tries to find if the local folder is the root folder.

the function: "isModuleRoot" stay in infinite loop.

**Comment by manuth** [comment]
Hello @jeffepalmares 
Thank you for using CallerModule

Sadly I wasn't able to find a function `isModuleRoot` in my module and in its dependencies.
Therefore I'm closing this issue now.
